##### Menu
menu:
  首页: /
  博文列表: /archives/
  关于: /about/
rss: /atom.xml

# Content
excerpt_link: Read More →
fancybox: true

# Sidebar
sidebar: right
widgets:
- category
# - tag
# - tagcloud
# - archive
- recent_posts
- recent_comments

# Miscellaneous
google_analytics: 
baidu_analytics: 
favicon: /favicon.ico
twitter:
google_plus:
fb_admins:
fb_app_id:


simple_search: https://www.google.com
