categories: Categories
search: Search
tags: Tags
tagcloud: Tag Cloud
prev: Prev
next: Next
comment: Comments
contents: Contents
archive_a: Archives
archive_b: "Archives: %s"
archive_date: "MMM YYYY"
page: Page %d
recent_posts: Recent Posts
recent_comments: Recent Comments
menu: Menu
links: Links
weibo: Weibo
rss: RSS
showsidebar: Show Sidebar
hidesidebar: Hide Sidebar
updated: Updated
totop: Back to Top
datepublished: Published
comments: Comments
older: Older
newer: Newer
blog_archives: Blog Archives
